=== eaoliveira/cursojavades/Desktop/workspace/CursoJavaDes/src/contato.dtd
<!ELEMENT contato (pessoa+) >
<!ELEMENT pessoa (nome, telefone, departamento, empresa) >
<!ELEMENT telefone (ddd, numero, ramal*) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT ddd (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT ramal (#PCDATA) >
<!ELEMENT departamento (#PCDATA) >
<!ELEMENT empresa (#PCDATA) >

=== eaoliveira/cursojavades/Desktop/workspace/CursoJavaDes/src/contato.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="contato.xsl"?>
<!DOCTYPE contato SYSTEM "contato.dtd">
<contato>
	<pessoa>
		<nome>Fulano1</nome>
		<telefone>
			<ddd>11</ddd>
			<numero>834928942 </numero>
			<ramal>11 </ramal>
		</telefone>
		<departamento>vendas</departamento>
		<empresa>fulano sa</empresa>
	</pessoa>
	<pessoa>
		<nome>Joao Ninguem</nome>
		<telefone>
			<ddd>21</ddd>
			<numero>465465652 </numero>
		</telefone>
		<departamento>marketing</departamento>
		<empresa>fulano sa</empresa>
	</pessoa>
		<pessoa>
		<nome>hsdfjklsd</nome>
		<telefone>
			<ddd>31</ddd>
			<numero>4556655454</numero>
		</telefone>
		<departamento>djskkl</departamento>
		<empresa>sddfa</empresa>
	</pessoa>
</contato>
